apiVersion: v1
kind: Service
metadata:
  name: {{ include "charts.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
      protocol: TCP
      name: http
  selector:
    app-full-name: {{ include "charts.fullname" . }}
