name: Build

on:
  push:
    branches:
      - master
      - develop
      - feat/ci

jobs:
  build-release:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Fetch applications version
        id: pomversion
        uses: mavrosxristoforos/get-xml-info@1.0
        with:
          xml-file: 'pom.xml'
          xpath: '/project/version/text()'

      - name: Debug msg
        run: echo "Let's build ${{ steps.pomversion.outputs.info }} version"

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: docker.pkg.github.com/BriceMichalski/on-manque-quoi-api/omq:${{ steps.pomversion.outputs.info }}
          secrets: |
            "github_token=${{ secrets.GITHUB_TOKEN }}"