name: Build

on:
  push:
    branches:
      - master
      - develop
      - feat/ci

jobs:
  build-release:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Set VERSION with pom.xml project version
        run: |
          version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout) && echo "::set-env name=VERSION::$version"
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

      - name: Debug msg
        run: echo "Let's build ${{ env.VERSION }} version"

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push version
        id: docker_build_version
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/bricemichalski/omq:${{ env.VERSION }}
          secrets: |
            "github_token=${{ secrets.GITHUB_TOKEN }}"

      - name: Build and push latest
        id: docker_build_preview
        uses: docker/build-push-action@v2
        if: $GITHUB_REF_NAME == 'develop'
        with:
          context: .
          push: true
          tags: ghcr.io/bricemichalski/omq:preview
          secrets: |
            "github_token=${{ secrets.GITHUB_TOKEN }}"

      - name: Build and push latest
        id: docker_build_latest
        uses: docker/build-push-action@v2
        if: $GITHUB_REF_NAME == 'master'
        with:
          context: .
          push: true
          tags: ghcr.io/bricemichalski/omq:latest
          secrets: |
            "github_token=${{ secrets.GITHUB_TOKEN }}"